### ISSUE TITLE
QToDoTxt won't run -- has File Not Found Error

### ISSUE THREAD

**Issue by BryansGH** [mNantern/QTodoTxt#114]
Edit added after further work. 
I managed to install a working qtodotxt by installing version 1.3 (which worked) and then upgrading to version 1.4. 
____________________

I used apt to install qtodotxt from the repository but, when attempting to run, received the error below. I checked and there was no ./qtodotxt.cfg file in the home directory as indicated by the error. Adding an empty file with that name resulted in a different error.  I uninstalled and reinstalled using Synaptic with the same result. I am running Debian Crunchbang and am up-to-date. 

prompt$ qtodotxt
Traceback (most recent call last):
  File "/usr/share/qtodotxt/bin/../qtodotxt/lib/settings.py", line 16, in load
    with open(self._file, 'tr') as file:
IOError: [Errno 2] No such file or directory: '/home/bryans/.qtodotxt.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 13, in <module>
    app.run()
  File "/usr/share/qtodotxt/bin/../qtodotxt/app.py", line 63, in run
    controller.show()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 63, in show
    self._settings.load()
  File "/usr/share/qtodotxt/bin/../qtodotxt/lib/settings.py", line 22, in load
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**Comment by funkyfuture** [comment]
since my fix is merged, this issue can be closed, right?

**Comment by mNantern** [comment]
Yep, you are right !
Thanks

**Comment by aurisnoctis** [comment]
This issue is still present in version 1.4.0 that I downloaded a few minutes ago from using the repository. Until the fix is in the official new version / repository, new users can create the file
`/home/<your user name>/.qtodotxt.cfg`
by hand, and copy the text provided by @baile above inside (entries can later be changed from inside the app via `File > Preferences`). I only adapted `"last_open_file": "/home/baile/todo.txt",`.

Thanks for a beautiful app I can use on Linux Mint!
